---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: 'Test GitHub Action ðŸ§ª'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  # Cannot be tested on pull request; secrets not available
  push:
    branches: ['main']

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

permissions: {}

env:
  tag: '0.0.1-dev0'

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: 'Test local GitHub Action'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: 'Checkout repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Perform setup prior to running test(s)
      - name: 'Checkout sample project repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: "lfreleng-actions/test-python-project"
          path: 'test-python-project'

      - name: 'Build Python project'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/python-build-action@8f567398591014dd5627961aaa9ec17816b072f0 # v1.0.2
        with:
          tag: "${{ env.tag }}"
          path_prefix: 'test-python-project'

      - name: "Running local action: ${{ github.repository }}"
        uses: ./
        with:
          path_prefix: 'test-python-project'
          tag: "${{ env.tag }}"
          no_checkout: true
          op_service_account_token: "${{ secrets.op_service_account_token }}"
          one_password_item: "${{ vars.one_password_item }}"
          pypi_credential: "${{ secrets.pypi_credential }}"
          publish_disable: true
